=== Blaise1030/c0nfig/apps/www/public/cli/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": { "type": "string" },
    "title": { "type": "string" },
    "description": { "type": "string" },
    "version": { "type": "number" },
    "operation": {
      "type": "array",
      "items": { "$ref": "#/definitions/Operation" }
    }
  },
  "required": ["title", "description", "operation"],
  "additionalProperties": false,
  "definitions": {
    "Operation": {
      "oneOf": [
        { "$ref": "#/definitions/InputOperation" },
        { "$ref": "#/definitions/AddOperation" },
        { "$ref": "#/definitions/AddImportOperation" },
        { "$ref": "#/definitions/AddExportOperation" },
        { "$ref": "#/definitions/InstallOperation" },
        { "$ref": "#/definitions/SelectOperation" },
        { "$ref": "#/definitions/ReadJSONOperation" },
        { "$ref": "#/definitions/UpdateJSONOperation" },
        { "$ref": "#/definitions/ConditionalOperation" }
      ]
    },
    "OperationArray": {
      "type": "array",
      "items": { "$ref": "#/definitions/Operation" }
    },
    "Selection": {
      "type": "object",
      "properties": {
        "label": { "type": "string" },
        "value": { "type": "string" }
      },
      "required": ["label", "value"],
      "additionalProperties": false
    },
    "InputOperation": {
      "type": "object",
      "properties": {
        "op": { "const": "input" },
        "title": { "type": "string" },
        "defaultValue": { "type": "string" },
        "value": { "type": "string" },
        "actions": { "$ref": "#/definitions/OperationArray" }
      },
      "required": ["op", "title", "defaultValue", "value", "actions"],
      "additionalProperties": false
    },
    "AddOperation": {
      "type": "object",
      "properties": {
        "op": { "const": "add" },
        "remoteSrc": { "type": "string" },
        "targetSrc": { "type": "string" }
      },
      "required": ["op", "remoteSrc", "targetSrc"],
      "additionalProperties": false
    },
    "AddImportOperation": {
      "type": "object",
      "properties": {
        "op": { "const": "add-import" },
        "targetSrc": { "type": "string" },
        "content": { "type": "string" }
      },
      "required": ["op", "targetSrc", "content"],
      "additionalProperties": false
    },
    "AddExportOperation": {
      "type": "object",
      "properties": {
        "op": { "const": "add-export" },
        "targetSrc": { "type": "string" },
        "content": { "type": "string" }
      },
      "required": ["op", "targetSrc", "content"],
      "additionalProperties": false
    },
    "InstallOperation": {
      "type": "object",
      "properties": {
        "op": { "const": "install" },
        "dep": {
          "type": "array",
          "items": { "type": "string" }
        },
        "devDep": {
          "type": "array",
          "items": { "type": "string" }
        }
      },
      "required": ["op", "dep"],
      "additionalProperties": false
    },
    "SelectOperation": {
      "type": "object",
      "properties": {
        "op": { "const": "select" },
        "title": { "type": "string" },
        "selections": {
          "type": "array",
          "items": { "$ref": "#/definitions/Selection" }
        },
        "value": { "type": "string" },
        "values": {
          "type": "object",
          "additionalProperties": { "$ref": "#/definitions/OperationArray" }
        }
      },
      "required": ["op", "title", "selections", "value", "values"],
      "additionalProperties": false
    },
    "ReadJSONOperation": {
      "type": "object",
      "properties": {
        "op": { "const": "readJSON" },
        "targetSrc": { "type": "string" },
        "value": { "type": "string" },
        "path": { "type": "string" },
        "values": {
          "type": "object",
          "additionalProperties": { "$ref": "#/definitions/OperationArray" }
        }
      },
      "required": ["op", "targetSrc", "path", "values"],
      "additionalProperties": false
    },
    "UpdateJSONOperation": {
      "type": "object",
      "properties": {
        "op": { "const": "updateJSON" },
        "targetSrc": { "type": "string" },
        "path": { "type": "string" },
        "value": { "type": "string" }
      },
      "required": ["op", "targetSrc", "path", "value"],
      "additionalProperties": false
    },
    "ConditionalOperation": {
      "type": "object",
      "properties": {
        "op": { "const": "conditional" },
        "condition": { "type": "string" },
        "then": { "$ref": "#/definitions/OperationArray" },
        "else": { "$ref": "#/definitions/OperationArray" }
      },
      "required": ["op", "condition", "then"],
      "additionalProperties": false
    }
  }
}

=== Blaise1030/c0nfig/apps/www/public/cli/db.json
{
  "$schema": "https://c0nfig.vercel.app/cli/schema.json",
  "description": "Initialize Drizzle ORM and Drizzle Kit to your project",
  "title": "Drizzle ORM and Drizzle Kit",
  "version": 1.0,
  "operation": [
    {
      "op": "select",
      "title": "Select your database type",
      "selections": [
        {"label": "Turso (SQLite)", "value": "turso"},
        {"label": "Supabase", "value": "supabase"},
        {"label": "SQLite", "value": "sqlite"}
      ],
      "value": "$databaseType",
      "values": {
        "turso": [
          {
            "op": "add",
            "content": "import { defineConfig } from 'drizzle-kit';\n\nexport default defineConfig({\n  schema: '$absDbPath/schema.ts',\n  out: '$absDbPath/migrations',\n  dialect: 'sqlite',\n  driver: 'turso',\n  verbose: true,\n  strict: true,\n  dbCredentials: {\n    authToken: process.env.DATABASE_AUTH as string,\n    url: process.env.DATABASE_URL as string\n  }\n});",
            "targetSrc": "./drizzle.config.ts"
          },
          {
            "op": "add",
            "content": "import { drizzle } from 'drizzle-orm/libsql';\nimport { createClient } from '@libsql/client';\nexport * from \"./schema\";\n\nconst client = createClient({ url: process.env.VITE_DATABASE_URL, authToken: process.env.DATABASE_TOKEN });\nexport const db = drizzle(client);",
            "targetSrc": "~/db/index.ts"
          },
          {
            "op": "add",
            "content": "import { sqliteTable, text } from \"drizzle-orm/sqlite-core\";\n\nexport const users = sqliteTable('users', { id: text('id') });",
            "targetSrc": "~/db/schema.ts"
          },
          {"op": "install", "dep": ["@libsql/client"]},
          {
            "op": "updateJSON",
            "targetSrc": "./command.config.json",
            "path": "db.engine",
            "value": "sqlite"
          },
          {
            "op": "updateJSON",
            "targetSrc": "./command.config.json",
            "path": "db.name",
            "value": "turso"
          }
        ],
        "supabase": [
          {
            "op": "add",
            "content": "import { defineConfig } from 'drizzle-kit';\n\nexport default defineConfig({\n  schema: '$absDbPath/schema.ts',\n  out: '$absDbPath/migrations',\n  dialect: 'postgresql',\n  verbose: true,\n  strict: true,\n  dbCredentials: {\n    url: process.env.DATABASE_URL as string\n  }\n});",
            "targetSrc": "./drizzle.config.ts"
          },
          {
            "op": "add",
            "content": "import { drizzle } from 'drizzle-orm/postgres-js';\nimport postgres from 'postgres';\nexport * from \"./schema\";\n\nconst connectionString = process.env.DATABASE_URL;\nconst client = postgres(connectionString);\nexport const db = drizzle(client);",
            "targetSrc": "~/db/index.ts"
          },
          {
            "op": "add",
            "content": "import { pgTable, serial } from \"drizzle-orm/pg-core\";\n\nexport const users = pgTable('users', {\n  id: serial('id').primaryKey(),\n});",
            "targetSrc": "~/db/schema.ts"
          },
          {"op": "install", "dep": ["postgres"]},
          {
            "op": "updateJSON",
            "targetSrc": "./command.config.json",
            "path": "db.engine",
            "value": "postgres"
          },
          {
            "op": "updateJSON",
            "targetSrc": "./command.config.json",
            "path": "db.name",
            "value": "supabase"
          }
        ],
        "sqlite": [
          {
            "op": "add",
            "content": "import { defineConfig } from 'drizzle-kit';\n\nexport default defineConfig({\n  schema: '$absDbPath/schema.ts',\n  out: '$absDbPath/migrations',\n  dialect: 'sqlite',\n  verbose: true,\n  strict: true,\n  dbCredentials: {\n    url: 'sqlite.db'\n  }\n});",
            "targetSrc": "./drizzle.config.ts"
          },
          {
            "op": "add",
            "content": "import { drizzle } from 'drizzle-orm/better-sqlite3';\nexport * from \"./schema\";\n\nimport Database from 'better-sqlite3';\nconst sqlite = new Database('sqlite.db');\nexport const db = drizzle(sqlite);",
            "targetSrc": "~/db/index.ts"
          },
          {
            "op": "add",
            "content": "import { text, sqliteTable } from \"drizzle-orm/sqlite-core\";\n\nexport const users = sqliteTable('users', {\n  id: text('id'),\n});",
            "targetSrc": "~/db/schema.ts"
          },
          {"op": "install", "dep": ["better-sqlite3"]},
          {
            "op": "updateJSON",
            "targetSrc": "./command.config.json",
            "path": "db.engine",
            "value": "sqlite"
          },
          {
            "op": "updateJSON",
            "targetSrc": "./command.config.json",
            "path": "db.name",
            "value": "sqlite"
          }
        ]
      }
    },
    {
      "op": "updateJSON",
      "targetSrc": "./package.json",
      "path": "scripts.db:generate",
      "value": "drizzle-kit generate"
    },
    {
      "op": "updateJSON",
      "targetSrc": "./package.json",
      "path": "scripts.db:migrate",
      "value": "drizzle-kit migrate"
    },
    {
      "op": "updateJSON",
      "targetSrc": "./package.json",
      "path": "scripts.db:push",
      "value": "drizzle-kit push"
    },
    {
      "op": "install",
      "dep": ["drizzle-orm"],
      "devDep": ["drizzle-kit"]
    }
  ]
}

=== Blaise1030/c0nfig/apps/www/public/cli/auth-add.json
{
  "$schema": "https://c0nfig.vercel.app/cli/schema.json",
  "description": "Initialize Lucia with Drizzle ORM",
  "title": "Lucia init",
  "version": 1.0,
  "operation": [
    {
      "op": "select",
      "title": "Select your auth type to add",
      "selections": [
        {"label": "Password", "value": "password"},
        {"label": "Google", "value": "google"},
        {"label": "Github", "value": "github"},
        {"label": "Discord", "value": "discord"}
      ],
      "value": "$authAdd",
      "values": {
        "password": [
          {
            "op": "add",
            "remoteSrc": "/assets/auth/options/password.ts",
            "targetSrc": "~/auth/options/password.ts"
          },
          {
            "op": "add-export",
            "targetSrc": "~/auth/options/index.ts",
            "content": "export * from './password'"
          },
          {
            "op": "install",
            "dep": ["zod"]
          }
        ],
        "google": [
          {
            "op": "add",
            "remoteSrc": "/assets/auth/options/google.ts",
            "targetSrc": "~/auth/options/google.ts"
          },
          {
            "op": "add-export",
            "targetSrc": "~/auth/options/index.ts",
            "content": "export * from './google'"
          }
        ],
        "github": [
          {
            "op": "add",
            "remoteSrc": "/assets/auth/options/github.ts",
            "targetSrc": "~/auth/options/github.ts"
          },
          {
            "op": "add-export",
            "targetSrc": "~/auth/options/index.ts",
            "content": "export * from './github'"
          }
        ],
        "discord": [
          {
            "op": "add",
            "remoteSrc": "/assets/auth/options/discord.ts",
            "targetSrc": "~/auth/options/discord.ts"
          },
          {
            "op": "add-export",
            "targetSrc": "~/auth/options/index.ts",
            "content": "export * from './discord'"
          }
        ]
      }
    }
  ]
}

=== Blaise1030/c0nfig/apps/www/public/cli/init.json
{
  "$schema": "https://c0nfig.vercel.app/cli/schema.json",
  "description": "Init your c0nfig framework",
  "title": "Init c0nfig",
  "version": 1.0,
  "operation": [
    {
      "op": "input",
      "title": "Which is your source directory",
      "defaultValue": "./src/*",
      "value": "$aliases",
      "actions": [
        {
          "op": "add",
          "content": "{}",
          "targetSrc": "./command.config.json"
        },
        {
          "op": "updateJSON",
          "targetSrc": "./command.config.json",
          "path": "aliases.path",
          "value": "$aliases"
        },
        {
          "op": "updateJSON",
          "targetSrc": "./package.json",
          "path": "imports.~/*",
          "value": "$aliases"
        },
        {
          "op": "updateJSON",
          "targetSrc": "./package.json",
          "path": "compilerOptions.paths.~/*[0]",
          "value": "./modules/*"
        }
      ]
    },
    {
      "op": "select",
      "title": "Select you package manager",
      "selections": [
        {"label": "npm", "value": "npm"},
        {"label": "pnpm", "value": "pnpm"},
        {"label": "yarn", "value": "yarn"}
      ],
      "value": "$packageManager",
      "values": {
        "npm": [
          {
            "op": "updateJSON",
            "targetSrc": "./command.config.json",
            "path": "packageManager",
            "value": "npm"
          }
        ],
        "pnpm": [
          {
            "op": "updateJSON",
            "targetSrc": "./command.config.json",
            "path": "packageManager",
            "value": "pnpm"
          }
        ],
        "yarn": [
          {
            "op": "updateJSON",
            "targetSrc": "./command.config.json",
            "path": "packageManager",
            "value": "yarn"
          }
        ]
      }
    }
  ]
}
